export const ADD_POKEMON = "ADD_POKEMON";
export const USER_NAVIGATION = "USER_NAVIGATION";
export const ADD_POKEMON_LIST = "ADD_POKEMON_LIST";
export const USER_TYPE = "USER_TYPE";
export const FETCH_POKEMON_START = "FETCH_POKEMON_START";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_FAILURE = "FETCH_POKEMON_FAILURE";
export const SET_PAGE = "SET_PAGE";
